// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOf-e7SdFHzxmOanf_IraApFCcjG55jm8',
    appId: '1:127122623184:web:e87b34b8b6b202e4dbecd5',
    messagingSenderId: '127122623184',
    projectId: 'firstmyapp-2025',
    authDomain: 'firstmyapp-2025.firebaseapp.com',
    storageBucket: 'firstmyapp-2025.firebasestorage.app',
    measurementId: 'G-2EST16H6WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANUxM8EtSiQsKmehi1G5osnZAMtq-YU2U',
    appId: '1:127122623184:android:20cab2c983b1d04cdbecd5',
    messagingSenderId: '127122623184',
    projectId: 'firstmyapp-2025',
    storageBucket: 'firstmyapp-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSupOxY-utReDNIw1HZBdS5L3CqiVZPmI',
    appId: '1:127122623184:ios:5408ad5d9e7b0484dbecd5',
    messagingSenderId: '127122623184',
    projectId: 'firstmyapp-2025',
    storageBucket: 'firstmyapp-2025.firebasestorage.app',
    iosBundleId: 'com.nithin.myappfirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSupOxY-utReDNIw1HZBdS5L3CqiVZPmI',
    appId: '1:127122623184:ios:5408ad5d9e7b0484dbecd5',
    messagingSenderId: '127122623184',
    projectId: 'firstmyapp-2025',
    storageBucket: 'firstmyapp-2025.firebasestorage.app',
    iosBundleId: 'com.nithin.myappfirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOf-e7SdFHzxmOanf_IraApFCcjG55jm8',
    appId: '1:127122623184:web:a5f4a841e97908efdbecd5',
    messagingSenderId: '127122623184',
    projectId: 'firstmyapp-2025',
    authDomain: 'firstmyapp-2025.firebaseapp.com',
    storageBucket: 'firstmyapp-2025.firebasestorage.app',
    measurementId: 'G-0EYVM16ZVY',
  );
}
